// SPDX-FileCopyrightText: 2025 Rifat Hasan <atunutemp1@gmail.com>
//
// SPDX-License-Identifier: MIT

/* Generated by the Nim Compiler v2.2.4 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
var NTI134217749 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217751 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217741 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217743 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555167 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555175 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33554449 = {size: 0,kind: 28,base: null,node: null,finalizer: null};
var NTI33554450 = {size: 0,kind: 29,base: null,node: null,finalizer: null};
var NTI33555174 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33555171 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555172 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NNI33555172 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555172.node = NNI33555172;
NTI33555174.base = NTI33555171;
NTI33555175.base = NTI33555171;
var NNI33555171 = {kind: 2, len: 5, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "parent", len: 0, typ: NTI33555174, name: "parent", sons: null}, 
{kind: 1, offset: "name", len: 0, typ: NTI33554450, name: "name", sons: null}, 
{kind: 1, offset: "message", len: 0, typ: NTI33554449, name: "msg", sons: null}, 
{kind: 1, offset: "trace", len: 0, typ: NTI33554449, name: "trace", sons: null}, 
{kind: 1, offset: "up", len: 0, typ: NTI33555175, name: "up", sons: null}]};
NTI33555171.node = NNI33555171;
var NNI33555167 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555167.node = NNI33555167;
NTI33555171.base = NTI33555167;
NTI33555172.base = NTI33555171;
var NNI134217743 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217743.node = NNI134217743;
var NNI134217741 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217741.node = NNI134217741;
NTI134217741.base = NTI33555172;
NTI134217743.base = NTI134217741;
var NNI134217751 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217751.node = NNI134217751;
NTI134217751.base = NTI33555172;
var NNI134217749 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217749.node = NNI134217749;
NTI134217749.base = NTI33555172;

function isObj(obj_p0, subclass_p1) {
  var result_33557443 = false;

  BeforeRet: {
    var x_33557444 = obj_p0;
    if ((x_33557444 == subclass_p1)) {
    result_33557443 = true;
    break BeforeRet;
    }
    
    Label1: {
        Label2: while (true) {
        if (!!((x_33557444 == subclass_p1))) break Label2;
          if ((x_33557444 == null)) {
          result_33557443 = false;
          break BeforeRet;
          }
          
          x_33557444 = x_33557444.base;
        }
    };
    result_33557443 = true;
    break BeforeRet;
  };

  return result_33557443;

}

function toJSStr(s_p0) {
  var result_33556919 = null;

    var res_33556973 = newSeq__system_u2516((s_p0).length);
    var i_33556974 = 0;
    var j_33556975 = 0;
    Label1: {
        Label2: while (true) {
        if (!(i_33556974 < (s_p0).length)) break Label2;
          var c_33556976 = s_p0[i_33556974];
          if ((c_33556976 < 128)) {
          res_33556973[j_33556975] = String.fromCharCode(c_33556976);
          i_33556974 += 1;
          }
          else {
            var helper_33557002 = newSeq__system_u2516(0);
            Label3: {
                Label4: while (true) {
                if (!true) break Label4;
                  var code_33557003 = c_33556976.toString(16);
                  if ((((code_33557003) == null ? 0 : (code_33557003).length) == 1)) {
                  helper_33557002.push("%0");;
                  }
                  else {
                  helper_33557002.push("%");;
                  }
                  
                  helper_33557002.push(code_33557003);;
                  i_33556974 += 1;
                  if ((((s_p0).length <= i_33556974) || (s_p0[i_33556974] < 128))) {
                  break Label3;
                  }
                  
                  c_33556976 = s_p0[i_33556974];
                }
            };
++excHandler;
            try {
            res_33556973[j_33556975] = decodeURIComponent(helper_33557002.join(""));
--excHandler;
} catch (EXCEPTION) {
 var prevJSError = lastJSError;
 lastJSError = EXCEPTION;
 --excHandler;
            raiseDefect();
            res_33556973[j_33556975] = helper_33557002.join("");
            lastJSError = prevJSError;
            } finally {
            }
          }
          
          j_33556975 += 1;
        }
    };
    if (res_33556973.length < j_33556975) { for (var i = res_33556973.length ; i < j_33556975 ; ++i) res_33556973.push(null); }
               else { res_33556973.length = j_33556975; };
    result_33556919 = res_33556973.join("");

  return result_33556919;

}

function rawEcho() {
          var buf = "";
      for (var i = 0; i < arguments.length; ++i) {
        buf += toJSStr(arguments[i]);
      }
      console.log(buf);
    

  
}

function setConstr() {
        var result = {};
    for (var i = 0; i < arguments.length; ++i) {
      var x = arguments[i];
      if (typeof(x) == "object") {
        for (var j = x[0]; j <= x[1]; ++j) {
          result[j] = true;
        }
      } else {
        result[x] = true;
      }
    }
    return result;
  

  
}
var ConstSet1 = setConstr(17, 16, 4, 18, 27, 19, 23, 22, 21);

function nimCopy(dest_p0, src_p1, ti_p2) {
  var result_33557330 = null;

    switch (ti_p2.kind) {
    case 21:
    case 22:
    case 23:
    case 5:
      if (!(isFatPointer__system_u2878(ti_p2))) {
      result_33557330 = src_p1;
      }
      else {
        result_33557330 = [src_p1[0], src_p1[1]];
      }
      
      break;
    case 19:
            if (dest_p0 === null || dest_p0 === undefined) {
        dest_p0 = {};
      }
      else {
        for (var key in dest_p0) { delete dest_p0[key]; }
      }
      for (var key in src_p1) { dest_p0[key] = src_p1[key]; }
      result_33557330 = dest_p0;
    
      break;
    case 18:
    case 17:
      if (!((ti_p2.base == null))) {
      result_33557330 = nimCopy(dest_p0, src_p1, ti_p2.base);
      }
      else {
      if ((ti_p2.kind == 17)) {
      result_33557330 = (dest_p0 === null || dest_p0 === undefined) ? {m_type: ti_p2} : dest_p0;
      }
      else {
        result_33557330 = (dest_p0 === null || dest_p0 === undefined) ? {} : dest_p0;
      }
      }
      nimCopyAux(result_33557330, src_p1, ti_p2.node);
      break;
    case 4:
    case 16:
            if(ArrayBuffer.isView(src_p1)) { 
        if(dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
          dest_p0 = new src_p1.constructor(src_p1);
        } else {
          dest_p0.set(src_p1, 0);
        }
        result_33557330 = dest_p0;
      } else {
        if (src_p1 === null) {
          result_33557330 = null;
        }
        else {
          if (dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
            dest_p0 = new Array(src_p1.length);
          }
          result_33557330 = dest_p0;
          for (var i = 0; i < src_p1.length; ++i) {
            result_33557330[i] = nimCopy(result_33557330[i], src_p1[i], ti_p2.base);
          }
        }
      }
    
      break;
    case 24:
    case 27:
            if (src_p1 === null) {
        result_33557330 = null;
      }
      else {
        if (dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
          dest_p0 = new Array(src_p1.length);
        }
        result_33557330 = dest_p0;
        for (var i = 0; i < src_p1.length; ++i) {
          result_33557330[i] = nimCopy(result_33557330[i], src_p1[i], ti_p2.base);
        }
      }
    
      break;
    case 28:
            if (src_p1 !== null) {
        result_33557330 = src_p1.slice(0);
      }
    
      break;
    default: 
      result_33557330 = src_p1;
      break;
    }

  return result_33557330;

}

function raiseException(e_p0, ename_p1) {
    e_p0.name = ename_p1;
    if ((excHandler == 0)) {
    unhandledException(e_p0);
    }
    
    throw e_p0;

  
}

function addInt(a_p0, b_p1) {
        var result = a_p0 + b_p1;
    checkOverflowInt(result);
    return result;
  

  
}

function mnewString(len_p0) {
        var result = new Array(len_p0);
    for (var i = 0; i < len_p0; i++) {result[i] = 0;}
    return result;
  

  
}

function nimCharToStr(x_p0) {
  var result_33556448 = [];

    result_33556448 = nimCopy(null, mnewString(1), NTI33554449);
    result_33556448[0] = x_p0;

  return result_33556448;

}

function cstrToNimstr(c_p0) {
      var ln = c_p0.length;
  var result = new Array(ln);
  var r = 0;
  for (var i = 0; i < ln; ++i) {
    var ch = c_p0.charCodeAt(i);

    if (ch < 128) {
      result[r] = ch;
    }
    else {
      if (ch < 2048) {
        result[r] = (ch >> 6) | 192;
      }
      else {
        if (ch < 55296 || ch >= 57344) {
          result[r] = (ch >> 12) | 224;
        }
        else {
            ++i;
            ch = 65536 + (((ch & 1023) << 10) | (c_p0.charCodeAt(i) & 1023));
            result[r] = (ch >> 18) | 240;
            ++r;
            result[r] = ((ch >> 12) & 63) | 128;
        }
        ++r;
        result[r] = ((ch >> 6) & 63) | 128;
      }
      ++r;
      result[r] = (ch & 63) | 128;
    }
    ++r;
  }
  return result;
  

  
}

function chckRange(i_p0, a_p1, b_p2) {
  var result_33557370 = 0;

  BeforeRet: {
    if (((a_p1 <= i_p0) && (i_p0 <= b_p2))) {
    result_33557370 = i_p0;
    break BeforeRet;
    }
    else {
    raiseRangeError();
    }
    
  };

  return result_33557370;

}

function chckIndx(i_p0, a_p1, b_p2) {
  var result_33557365 = 0;

  BeforeRet: {
    if (((a_p1 <= i_p0) && (i_p0 <= b_p2))) {
    result_33557365 = i_p0;
    break BeforeRet;
    }
    else {
    raiseIndexError(i_p0, a_p1, b_p2);
    }
    
  };

  return result_33557365;

}

function eqStrings(a_p0, b_p1) {
        if (a_p0 == b_p1) return true;
    if (a_p0 === null && b_p1.length == 0) return true;
    if (b_p1 === null && a_p0.length == 0) return true;
    if ((!a_p0) || (!b_p1)) return false;
    var alen = a_p0.length;
    if (alen != b_p1.length) return false;
    for (var i = 0; i < alen; ++i)
      if (a_p0[i] != b_p1[i]) return false;
    return true;
  

  
}

function newSeq__system_u2516(len_p0) {
  var result_33556952 = [];

    result_33556952 = new Array(len_p0); for (var i = 0 ; i < len_p0 ; ++i) { result_33556952[i] = null; }
  return result_33556952;

}

function isNimException__system_u2017() {
    return lastJSError && lastJSError.m_type;

  
}

function getCurrentException() {
  var result_33556452 = null;

    if (isNimException__system_u2017()) {
    result_33556452 = lastJSError;
    }
    

  return result_33556452;

}

function add__system_u1942(x_p0, x_p0_Idx, y_p1) {
          if (x_p0[x_p0_Idx] === null) { x_p0[x_p0_Idx] = []; }
      var off = x_p0[x_p0_Idx].length;
      x_p0[x_p0_Idx].length += y_p1.length;
      for (var i = 0; i < y_p1.length; ++i) {
        x_p0[x_p0_Idx][off+i] = y_p1.charCodeAt(i);
      }
    

  
}

function unhandledException(e_p0) {
    var buf_33556658 = [[]];
    if (!(((e_p0.message).length == 0))) {
    buf_33556658[0].push.apply(buf_33556658[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110,58,32]);;
    buf_33556658[0].push.apply(buf_33556658[0], e_p0.message);;
    }
    else {
    buf_33556658[0].push.apply(buf_33556658[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110]);;
    }
    
    buf_33556658[0].push.apply(buf_33556658[0], [32,91]);;
    add__system_u1942(buf_33556658, 0, e_p0.name);
    buf_33556658[0].push.apply(buf_33556658[0], [93,10]);;
    var cbuf_33556659 = toJSStr(buf_33556658[0]);
      if (typeof(Error) !== "undefined") {
    throw new Error(cbuf_33556659);
  }
  else {
    throw cbuf_33556659;
  }
  

  
}

function raiseDefect() {
    if (isNimException__system_u2017()) {
    var e_33556664 = getCurrentException();
    if (isObj(e_33556664.m_type, NTI33555172)) {
    if ((excHandler == 0)) {
    unhandledException(e_33556664);
    }
    
    throw e_33556664;
    }
    
    }
    

  
}

function noop__OOZtestsZnomuna_u40() {
    rawEcho([78,111,32,79,112,101,114,97,116,105,111,110]);

  
}

function noop() {
    noop__OOZtestsZnomuna_u40();

  
}

function extraNoOp__OOZtestsZnomuna_u44() {
    rawEcho([101,120,116,114,97,58,32,78,111,32,79,112,46]);

  
}

function extraNoOp() {
    extraNoOp__OOZtestsZnomuna_u44();

  
}

function constRet__OOZtestsZnomuna_u49() {
  var result_1090519090 = 0;

  BeforeRet: {
    result_1090519090 = 2;
    break BeforeRet;
  };

  return result_1090519090;

}

function constRet() {
  var result_939524102 = 0;

  BeforeRet: {
    result_939524102 = ((constRet__OOZtestsZnomuna_u49()) | 0);
    break BeforeRet;
  };

  return result_939524102;

}

function constRetBool__OOZtestsZnomuna_u51() {
  var result_1090519092 = false;

  BeforeRet: {
    result_1090519092 = true;
    break BeforeRet;
  };

  return result_1090519092;

}

function constRetBool() {
  var result_939524104 = false;

  BeforeRet: {
    result_939524104 = constRetBool__OOZtestsZnomuna_u51();
    break BeforeRet;
  };

  return result_939524104;

}

function constRetFloat__OOZtestsZnomuna_u53() {
  var result_1090519094 = 0.0;

  BeforeRet: {
    result_1090519094 = 2.3;
    break BeforeRet;
  };

  return result_1090519094;

}

function constRetFloat() {
  var result_939524106 = 0.0;

  BeforeRet: {
    result_939524106 = constRetFloat__OOZtestsZnomuna_u53();
    break BeforeRet;
  };

  return result_939524106;

}

function constRetChar__OOZtestsZnomuna_u55() {
  var result_1090519096 = 0;

  BeforeRet: {
    result_1090519096 = 97;
    break BeforeRet;
  };

  return result_1090519096;

}

function constRetChar() {
  var result_939524108 = 0;

  BeforeRet: {
    result_939524108 = constRetChar__OOZtestsZnomuna_u55();
    break BeforeRet;
  };

  return result_939524108;

}

function isFatPointer__system_u2878(ti_p0) {
  var result_33557312 = false;

  BeforeRet: {
    result_33557312 = !((ConstSet1[ti_p0.base.kind] != undefined));
    break BeforeRet;
  };

  return result_33557312;

}

function nimCopyAux(dest_p0, src_p1, n_p2) {
    switch (n_p2.kind) {
    case 0:
      break;
    case 1:
            dest_p0[n_p2.offset] = nimCopy(dest_p0[n_p2.offset], src_p1[n_p2.offset], n_p2.typ);
    
      break;
    case 2:
          for (var i = 0; i < n_p2.sons.length; i++) {
      nimCopyAux(dest_p0, src_p1, n_p2.sons[i]);
    }
    
      break;
    case 3:
            dest_p0[n_p2.offset] = nimCopy(dest_p0[n_p2.offset], src_p1[n_p2.offset], n_p2.typ);
      for (var i = 0; i < n_p2.sons.length; ++i) {
        nimCopyAux(dest_p0, src_p1, n_p2.sons[i][1]);
      }
    
      break;
    }

  
}

function constRetStr__OOZtestsZnomuna_u57() {
  var result_1090519098 = [];

  BeforeRet: {
    result_1090519098 = nimCopy(null, [119,104,97,116], NTI33554449);
    break BeforeRet;
  };

  return result_1090519098;

}

function constRetStr() {
  var result_939524110 = null;

  BeforeRet: {
    result_939524110 = toJSStr(constRetStr__OOZtestsZnomuna_u57());
    break BeforeRet;
  };

  return result_939524110;

}

function constRetUnicodeStr__OOZtestsZnomuna_u59() {
  var result_1090519100 = [];

  BeforeRet: {
    result_1090519100 = nimCopy(null, [224,166,170,224,167,141,224,166,176,224,167,139,224,166,151,224,167,141,224,166,176,224,166,190,224,166,174,224,166,191,224,166,130], NTI33554449);
    break BeforeRet;
  };

  return result_1090519100;

}

function constRetUnicodeStr() {
  var result_939524112 = null;

  BeforeRet: {
    result_939524112 = toJSStr(constRetUnicodeStr__OOZtestsZnomuna_u59());
    break BeforeRet;
  };

  return result_939524112;

}

function raiseOverflow() {
    raiseException({message: [111,118,101,114,45,32,111,114,32,117,110,100,101,114,102,108,111,119], parent: null, m_type: NTI134217743, name: null, trace: [], up: null}, "OverflowDefect");

  
}

function checkOverflowInt(a_p0) {
        if (a_p0 > 2147483647 || a_p0 < -2147483648) raiseOverflow();
  

  
}

function addIntNum__OOZtestsZnomuna_u61(a_p0, b_p1) {
  var result_1090519104 = 0;

  BeforeRet: {
    result_1090519104 = addInt(a_p0, b_p1);
    break BeforeRet;
  };

  return result_1090519104;

}

function addIntNum(a_p0, b_p1) {
  var result_939524116 = 0;

  BeforeRet: {
    result_939524116 = ((addIntNum__OOZtestsZnomuna_u61(((a_p0) | 0), ((b_p1) | 0))) | 0);
    break BeforeRet;
  };

  return result_939524116;

}

function printCond__OOZtestsZnomuna_u65(a_p0) {
    if (a_p0) {
    rawEcho([115,117,99,99,101,115,115]);
    }
    else {
    rawEcho([102,97,105,108,117,114,101]);
    }
    

  
}

function printCond(a_p0) {
    printCond__OOZtestsZnomuna_u65(a_p0);

  
}

function addDouble__OOZtestsZnomuna_u67(a_p0, b_p1) {
  var result_1090519110 = 0.0;

  BeforeRet: {
    result_1090519110 = (a_p0 + b_p1);
    break BeforeRet;
  };

  return result_1090519110;

}

function addDouble(a_p0, b_p1) {
  var result_939524122 = 0.0;

  BeforeRet: {
    result_939524122 = addDouble__OOZtestsZnomuna_u67(a_p0, b_p1);
    break BeforeRet;
  };

  return result_939524122;

}

function addFloat__OOZtestsZnomuna_u71(a_p0, b_p1) {
  var result_1090519114 = 0.0;

  BeforeRet: {
    result_1090519114 = (a_p0 + b_p1);
    break BeforeRet;
  };

  return result_1090519114;

}

function addFloat(a_p0, b_p1) {
  var result_939524126 = 0.0;

  BeforeRet: {
    result_939524126 = addFloat__OOZtestsZnomuna_u71(a_p0, b_p1);
    break BeforeRet;
  };

  return result_939524126;

}

function takeChar__OOZtestsZnomuna_u75(a_p0) {
    rawEcho(nimCharToStr(a_p0));

  
}

function takeChar(a_p0) {
    takeChar__OOZtestsZnomuna_u75(a_p0);

  
}

function printStr__OOZtestsZnomuna_u77(a_p0) {
    rawEcho(a_p0);

  
}

function printStr(a_p0) {
    printStr__OOZtestsZnomuna_u77(cstrToNimstr(a_p0));

  
}

function sayHello__OOZtestsZnomuna_u79(name_p0) {
  var result_1090519121 = [];

    result_1090519121 = nimCopy(null, ([72,195,169,108,108,195,184,32]).concat(name_p0), NTI33554449);

  return result_1090519121;

}

function sayHello(name_p0) {
  var result_939524133 = null;

  BeforeRet: {
    result_939524133 = toJSStr(sayHello__OOZtestsZnomuna_u79(cstrToNimstr(name_p0)));
    break BeforeRet;
  };

  return result_939524133;

}

function print2Str__OOZtestsZnomuna_u82(str1_p0, str2_p1) {
    rawEcho(str1_p0, [32], str2_p1);

  
}

function print2Str(str1_p0, str2_p1) {
    print2Str__OOZtestsZnomuna_u82(cstrToNimstr(str1_p0), cstrToNimstr(str2_p1));

  
}

function raiseRangeError() {
    raiseException({message: [118,97,108,117,101,32,111,117,116,32,111,102,32,114,97,110,103,101], parent: null, m_type: NTI134217751, name: null, trace: [], up: null}, "RangeDefect");

  
}

function raiseIndexError(i_p0, a_p1, b_p2) {
    var Temporary1;

    if ((b_p2 < a_p1)) {
    Temporary1 = [105,110,100,101,120,32,111,117,116,32,111,102,32,98,111,117,110,100,115,44,32,116,104,101,32,99,111,110,116,97,105,110,101,114,32,105,115,32,101,109,112,116,121];
    }
    else {
    Temporary1 = ([105,110,100,101,120,32]).concat(HEX24__systemZdollars_u14(i_p0),[32,110,111,116,32,105,110,32],HEX24__systemZdollars_u14(a_p1),[32,46,46,32],HEX24__systemZdollars_u14(b_p2));
    }
    
    raiseException({message: nimCopy(null, Temporary1, NTI33554449), parent: null, m_type: NTI134217749, name: null, trace: [], up: null}, "IndexDefect");

  
}

function addChars__stdZprivateZdigitsutils_u202(result_p0, result_p0_Idx, x_p1, start_p2, n_p3) {
    var Temporary1;

    var old_301990096 = (result_p0[result_p0_Idx]).length;
    if (result_p0[result_p0_Idx].length < (Temporary1 = chckRange(addInt(old_301990096, n_p3), 0, 2147483647), Temporary1)) { for (var i = result_p0[result_p0_Idx].length; i < Temporary1; ++i) result_p0[result_p0_Idx].push(0); }
         else {result_p0[result_p0_Idx].length = Temporary1; };
    Label2: {
      var iHEX60gensym4_301990110 = 0;
      var i_939524162 = 0;
      Label3: {
          Label4: while (true) {
          if (!(i_939524162 < n_p3)) break Label4;
            iHEX60gensym4_301990110 = i_939524162;
            result_p0[result_p0_Idx][chckIndx(addInt(old_301990096, iHEX60gensym4_301990110), 0, (result_p0[result_p0_Idx]).length - 1)] = x_p1.charCodeAt(chckIndx(addInt(start_p2, iHEX60gensym4_301990110), 0, (x_p1).length - 1));
            i_939524162 = addInt(i_939524162, 1);
          }
      };
    };

  
}

function addChars__stdZprivateZdigitsutils_u198(result_p0, result_p0_Idx, x_p1) {
    addChars__stdZprivateZdigitsutils_u202(result_p0, result_p0_Idx, x_p1, 0, ((x_p1) == null ? 0 : (x_p1).length));

  
}

function addInt__stdZprivateZdigitsutils_u223(result_p0, result_p0_Idx, x_p1) {
    addChars__stdZprivateZdigitsutils_u198(result_p0, result_p0_Idx, ((x_p1) + ""));

  
}

function addInt__stdZprivateZdigitsutils_u241(result_p0, result_p0_Idx, x_p1) {
    addInt__stdZprivateZdigitsutils_u223(result_p0, result_p0_Idx, BigInt(x_p1));

  
}

function HEX24__systemZdollars_u14(xHEX60gensym0_p0) {
  var result_385875984 = [[]];

    result_385875984[0] = nimCopy(null, [], NTI33554449);
    addInt__stdZprivateZdigitsutils_u241(result_385875984, 0, xHEX60gensym0_p0);

  return result_385875984[0];

}

function printDirectionRawValue__OOZtestsZnomuna_u101(direction_p0) {
    rawEcho([100,105,114,101,99,116,105,111,110,32,114,97,119,32,118,97,108,117,101,58,32], HEX24__systemZdollars_u14(direction_p0));

  
}

function printDirectionRawValue(direction_p0) {
    printDirectionRawValue__OOZtestsZnomuna_u101(direction_p0);

  
}

function getDirection__OOZtestsZnomuna_u123(hint_p0) {
    var Temporary1;

  var result_1090519165 = 0;

    if (eqStrings(hint_p0, [115,111,117,116,104])) {
    Temporary1 = 2;
    }
    else {
    Temporary1 = 1;
    }
    
    result_1090519165 = Temporary1;

  return result_1090519165;

}

function getDirection(hint_p0) {
  var result_939524141 = 0;

  BeforeRet: {
    result_939524141 = getDirection__OOZtestsZnomuna_u123(cstrToNimstr(hint_p0));
    break BeforeRet;
  };

  return result_939524141;

}

function getOpposite__OOZtestsZnomuna_u142(direction_p0) {
  var result_1090519184 = 0;

  BeforeRet: {
    switch (direction_p0) {
    case 0:
      result_1090519184 = 2;
      break BeforeRet;
      break;
    case 1:
      result_1090519184 = 3;
      break BeforeRet;
      break;
    case 2:
      result_1090519184 = 0;
      break BeforeRet;
      break;
    case 3:
      result_1090519184 = 1;
      break BeforeRet;
      break;
    }
  };

  return result_1090519184;

}

function getOpposite(direction_p0) {
  var result_939524144 = 0;

  BeforeRet: {
    result_939524144 = getOpposite__OOZtestsZnomuna_u142(direction_p0);
    break BeforeRet;
  };

  return result_939524144;

}

function togglePause__OOZtestsZnomuna_u145(curState_p0) {
  var result_1090519187 = 0;

  BeforeRet: {
    switch (curState_p0) {
    case 100:
      result_1090519187 = 101;
      break BeforeRet;
      break;
    case 101:
      result_1090519187 = 100;
      break BeforeRet;
      break;
    default: 
      result_1090519187 = curState_p0;
      break BeforeRet;
      break;
    }
  };

  return result_1090519187;

}

function togglePause(curState_p0) {
  var result_939524147 = 0;

  BeforeRet: {
    result_939524147 = togglePause__OOZtestsZnomuna_u145(curState_p0);
    break BeforeRet;
  };

  return result_939524147;

}

function find__stdZenumutils_u55(a_p0, item_p1) {
  var result_771751996 = 0;

  BeforeRet: {
    result_771751996 = 0;
    Label1: {
      var i_771752000 = [];
      var i_939524166 = 0;
      Label2: {
          Label3: while (true) {
          if (!(i_939524166 < (a_p0).length)) break Label3;
            i_771752000 = a_p0[chckIndx(i_939524166, 0, (a_p0).length - 1)];
            if (eqStrings(i_771752000, item_p1)) {
            break BeforeRet;
            }
            
            result_771751996 = addInt(result_771751996, 1);
            i_939524166 += 1;
          }
      };
    };
    result_771751996 = (-1);
  };

  return result_771751996;

}

function contains__stdZenumutils_u50(a_p0, item_p1) {
  var result_771751990 = false;

  BeforeRet: {
    result_771751990 = (0 <= find__stdZenumutils_u55(a_p0, item_p1));
    break BeforeRet;
  };

  return result_771751990;

}

function authenticate__OOZtestsZnomuna_u164(username_p0) {
  var result_1090519206 = 0;

  BeforeRet: {
    if (contains__stdZenumutils_u50([[97,100,109,105,110], [117,115,101,114]], username_p0)) {
    result_1090519206 = 200;
    break BeforeRet;
    }
    else {
      result_1090519206 = 401;
      break BeforeRet;
    }
    
  };

  return result_1090519206;

}

function authenticate(username_p0) {
  var result_939524150 = 0;

  BeforeRet: {
    result_939524150 = authenticate__OOZtestsZnomuna_u164(cstrToNimstr(username_p0));
    break BeforeRet;
  };

  return result_939524150;

}

function setGameState__OOZtestsZnomuna_u189(username_p0, state_p1) {
  var result_1090519232 = 0;

  BeforeRet: {
    var authResult_1090519233 = authenticate__OOZtestsZnomuna_u164(username_p0);
    if ((authResult_1090519233 == 401)) {
    result_1090519232 = 403;
    break BeforeRet;
    }
    
    if ((state_p1 == 102)) {
    result_1090519232 = 400;
    break BeforeRet;
    }
    
    result_1090519232 = 200;
    break BeforeRet;
  };

  return result_1090519232;

}

function setGameState(username_p0, state_p1) {
  var result_939524154 = 0;

  BeforeRet: {
    result_939524154 = setGameState__OOZtestsZnomuna_u189(cstrToNimstr(username_p0), state_p1);
    break BeforeRet;
  };

  return result_939524154;

}

const Direction = {
  North: 0,
  East: 1,
  South: 2,
  West: 3,
};

const GameState = {
  Playing: 100,
  Pause: 101,
  Game_over: 102,
};

const HttpStatusCode = {
  Ok: 200,
  Created: 201,
  No_content: 204,
  Moved_permanently: 301,
  Found: 302,
  Not_modified: 304,
  Bad_request: 400,
  Unauthorized: 401,
  Forbidden: 403,
  Not_found: 404,
  Internal_server_error: 500,
  Bad_gateway: 502,
  Service_unavailable: 503,
};


export { Direction, GameState, HttpStatusCode, noop, extraNoOp, constRet, constRetBool, constRetFloat, constRetChar, constRetStr, constRetUnicodeStr, addIntNum, printCond, addDouble, addFloat, takeChar, printStr, sayHello, print2Str, printDirectionRawValue, getDirection, getOpposite, togglePause, authenticate, setGameState };

